//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Data/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""0acb02a0-f8f4-4b39-bf6f-a9f9eb11118d"",
            ""actions"": [
                {
                    ""name"": ""ApplyMovement"",
                    ""type"": ""Button"",
                    ""id"": ""4614d3e5-e8b2-4db8-b97b-f7d470ede9c5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangeDirectionAndSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""77f3e0a6-d5ff-4f20-933c-895fd8359382"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SetRunSpeen"",
                    ""type"": ""Button"",
                    ""id"": ""b4498d5d-555e-4ffe-adcc-a309a2360911"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ApplyJump"",
                    ""type"": ""Button"",
                    ""id"": ""a14c67d2-2ba1-42f8-a882-9c27cf421de7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastFall"",
                    ""type"": ""Button"",
                    ""id"": ""aaf8eb42-7dd4-4058-ac1c-d127a8e44a15"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""6bd9a41b-7f05-4301-85fe-edabbb9507c6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDirectionAndSpeed"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e358e6f4-08f3-4c8f-aea2-2a0f189945df"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDirectionAndSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""c7895e22-fae1-4e8b-ac16-9e2d83461f34"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDirectionAndSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ac76bf16-1f39-4e8c-88af-9088ad5703cf"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ApplyMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""612934fd-54cf-4aff-a170-b515000260dd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ApplyMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ca13309-1a66-47e4-b25b-88d5d844a5e8"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetRunSpeen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c4fee08-86e4-46ae-aff9-cd9d051e47a6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ApplyJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""134f20ef-840e-4104-ac91-4fa52f949b89"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastFall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_ApplyMovement = m_Player.FindAction("ApplyMovement", throwIfNotFound: true);
        m_Player_ChangeDirectionAndSpeed = m_Player.FindAction("ChangeDirectionAndSpeed", throwIfNotFound: true);
        m_Player_SetRunSpeen = m_Player.FindAction("SetRunSpeen", throwIfNotFound: true);
        m_Player_ApplyJump = m_Player.FindAction("ApplyJump", throwIfNotFound: true);
        m_Player_FastFall = m_Player.FindAction("FastFall", throwIfNotFound: true);
    }

    ~@PlayerInputActions()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, PlayerInputActions.Player.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_ApplyMovement;
    private readonly InputAction m_Player_ChangeDirectionAndSpeed;
    private readonly InputAction m_Player_SetRunSpeen;
    private readonly InputAction m_Player_ApplyJump;
    private readonly InputAction m_Player_FastFall;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ApplyMovement => m_Wrapper.m_Player_ApplyMovement;
        public InputAction @ChangeDirectionAndSpeed => m_Wrapper.m_Player_ChangeDirectionAndSpeed;
        public InputAction @SetRunSpeen => m_Wrapper.m_Player_SetRunSpeen;
        public InputAction @ApplyJump => m_Wrapper.m_Player_ApplyJump;
        public InputAction @FastFall => m_Wrapper.m_Player_FastFall;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @ApplyMovement.started += instance.OnApplyMovement;
            @ApplyMovement.performed += instance.OnApplyMovement;
            @ApplyMovement.canceled += instance.OnApplyMovement;
            @ChangeDirectionAndSpeed.started += instance.OnChangeDirectionAndSpeed;
            @ChangeDirectionAndSpeed.performed += instance.OnChangeDirectionAndSpeed;
            @ChangeDirectionAndSpeed.canceled += instance.OnChangeDirectionAndSpeed;
            @SetRunSpeen.started += instance.OnSetRunSpeen;
            @SetRunSpeen.performed += instance.OnSetRunSpeen;
            @SetRunSpeen.canceled += instance.OnSetRunSpeen;
            @ApplyJump.started += instance.OnApplyJump;
            @ApplyJump.performed += instance.OnApplyJump;
            @ApplyJump.canceled += instance.OnApplyJump;
            @FastFall.started += instance.OnFastFall;
            @FastFall.performed += instance.OnFastFall;
            @FastFall.canceled += instance.OnFastFall;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @ApplyMovement.started -= instance.OnApplyMovement;
            @ApplyMovement.performed -= instance.OnApplyMovement;
            @ApplyMovement.canceled -= instance.OnApplyMovement;
            @ChangeDirectionAndSpeed.started -= instance.OnChangeDirectionAndSpeed;
            @ChangeDirectionAndSpeed.performed -= instance.OnChangeDirectionAndSpeed;
            @ChangeDirectionAndSpeed.canceled -= instance.OnChangeDirectionAndSpeed;
            @SetRunSpeen.started -= instance.OnSetRunSpeen;
            @SetRunSpeen.performed -= instance.OnSetRunSpeen;
            @SetRunSpeen.canceled -= instance.OnSetRunSpeen;
            @ApplyJump.started -= instance.OnApplyJump;
            @ApplyJump.performed -= instance.OnApplyJump;
            @ApplyJump.canceled -= instance.OnApplyJump;
            @FastFall.started -= instance.OnFastFall;
            @FastFall.performed -= instance.OnFastFall;
            @FastFall.canceled -= instance.OnFastFall;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnApplyMovement(InputAction.CallbackContext context);
        void OnChangeDirectionAndSpeed(InputAction.CallbackContext context);
        void OnSetRunSpeen(InputAction.CallbackContext context);
        void OnApplyJump(InputAction.CallbackContext context);
        void OnFastFall(InputAction.CallbackContext context);
    }
}
